// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: proto/mchost_ip_payload.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mchost_ip_payload_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mchost_ip_payload_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_mchost_ip_payload_proto_rawDescGZIP(), []int{0}
}

type DefaultResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error   bool   `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Code    uint32 `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DefaultResponse) Reset() {
	*x = DefaultResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mchost_ip_payload_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DefaultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultResponse) ProtoMessage() {}

func (x *DefaultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mchost_ip_payload_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultResponse.ProtoReflect.Descriptor instead.
func (*DefaultResponse) Descriptor() ([]byte, []int) {
	return file_proto_mchost_ip_payload_proto_rawDescGZIP(), []int{1}
}

func (x *DefaultResponse) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *DefaultResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DefaultResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateIpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	UserId int64  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *CreateIpRequest) Reset() {
	*x = CreateIpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mchost_ip_payload_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateIpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIpRequest) ProtoMessage() {}

func (x *CreateIpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mchost_ip_payload_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIpRequest.ProtoReflect.Descriptor instead.
func (*CreateIpRequest) Descriptor() ([]byte, []int) {
	return file_proto_mchost_ip_payload_proto_rawDescGZIP(), []int{2}
}

func (x *CreateIpRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateIpRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CreateIpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error          bool   `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Code           uint32 `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Message        string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	AllocationId   string `protobuf:"bytes,5,opt,name=allocationId,proto3" json:"allocationId,omitempty"`
	OwnerId        uint64 `protobuf:"varint,6,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	InstanceId     string `protobuf:"bytes,7,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	SpotInstanceId uint64 `protobuf:"varint,12,opt,name=spotInstanceId,proto3" json:"spotInstanceId,omitempty"`
	Name           string `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	Type           string `protobuf:"bytes,9,opt,name=type,proto3" json:"type,omitempty"`
	Region         string `protobuf:"bytes,10,opt,name=region,proto3" json:"region,omitempty"`
	Address        string `protobuf:"bytes,11,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *CreateIpResponse) Reset() {
	*x = CreateIpResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mchost_ip_payload_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateIpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIpResponse) ProtoMessage() {}

func (x *CreateIpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mchost_ip_payload_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIpResponse.ProtoReflect.Descriptor instead.
func (*CreateIpResponse) Descriptor() ([]byte, []int) {
	return file_proto_mchost_ip_payload_proto_rawDescGZIP(), []int{3}
}

func (x *CreateIpResponse) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *CreateIpResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateIpResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateIpResponse) GetAllocationId() string {
	if x != nil {
		return x.AllocationId
	}
	return ""
}

func (x *CreateIpResponse) GetOwnerId() uint64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *CreateIpResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *CreateIpResponse) GetSpotInstanceId() uint64 {
	if x != nil {
		return x.SpotInstanceId
	}
	return 0
}

func (x *CreateIpResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateIpResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateIpResponse) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *CreateIpResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetIpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IpId int64 `protobuf:"varint,1,opt,name=ipId,proto3" json:"ipId,omitempty"`
}

func (x *GetIpRequest) Reset() {
	*x = GetIpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mchost_ip_payload_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIpRequest) ProtoMessage() {}

func (x *GetIpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mchost_ip_payload_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIpRequest.ProtoReflect.Descriptor instead.
func (*GetIpRequest) Descriptor() ([]byte, []int) {
	return file_proto_mchost_ip_payload_proto_rawDescGZIP(), []int{4}
}

func (x *GetIpRequest) GetIpId() int64 {
	if x != nil {
		return x.IpId
	}
	return 0
}

type GetIpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error   bool   `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Code    uint32 `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Ip      *Ip    `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
}

func (x *GetIpResponse) Reset() {
	*x = GetIpResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mchost_ip_payload_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIpResponse) ProtoMessage() {}

func (x *GetIpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mchost_ip_payload_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIpResponse.ProtoReflect.Descriptor instead.
func (*GetIpResponse) Descriptor() ([]byte, []int) {
	return file_proto_mchost_ip_payload_proto_rawDescGZIP(), []int{5}
}

func (x *GetIpResponse) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *GetIpResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetIpResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetIpResponse) GetIp() *Ip {
	if x != nil {
		return x.Ip
	}
	return nil
}

type DeleteIpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IpId int64 `protobuf:"varint,1,opt,name=ipId,proto3" json:"ipId,omitempty"`
}

func (x *DeleteIpRequest) Reset() {
	*x = DeleteIpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mchost_ip_payload_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteIpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIpRequest) ProtoMessage() {}

func (x *DeleteIpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mchost_ip_payload_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIpRequest.ProtoReflect.Descriptor instead.
func (*DeleteIpRequest) Descriptor() ([]byte, []int) {
	return file_proto_mchost_ip_payload_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteIpRequest) GetIpId() int64 {
	if x != nil {
		return x.IpId
	}
	return 0
}

type DeleteIpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error   bool   `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Code    uint32 `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DeleteIpResponse) Reset() {
	*x = DeleteIpResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mchost_ip_payload_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteIpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIpResponse) ProtoMessage() {}

func (x *DeleteIpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mchost_ip_payload_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIpResponse.ProtoReflect.Descriptor instead.
func (*DeleteIpResponse) Descriptor() ([]byte, []int) {
	return file_proto_mchost_ip_payload_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteIpResponse) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *DeleteIpResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteIpResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReserveIpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IpId                   int64  `protobuf:"varint,1,opt,name=ipId,proto3" json:"ipId,omitempty"`
	SpotInstanceTemplateId uint64 `protobuf:"varint,2,opt,name=spotInstanceTemplateId,proto3" json:"spotInstanceTemplateId,omitempty"`
}

func (x *ReserveIpRequest) Reset() {
	*x = ReserveIpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mchost_ip_payload_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReserveIpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveIpRequest) ProtoMessage() {}

func (x *ReserveIpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mchost_ip_payload_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveIpRequest.ProtoReflect.Descriptor instead.
func (*ReserveIpRequest) Descriptor() ([]byte, []int) {
	return file_proto_mchost_ip_payload_proto_rawDescGZIP(), []int{8}
}

func (x *ReserveIpRequest) GetIpId() int64 {
	if x != nil {
		return x.IpId
	}
	return 0
}

func (x *ReserveIpRequest) GetSpotInstanceTemplateId() uint64 {
	if x != nil {
		return x.SpotInstanceTemplateId
	}
	return 0
}

type ReserveIpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error           bool   `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Code            uint32 `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Message         string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	EipAllocationId string `protobuf:"bytes,4,opt,name=eipAllocationId,proto3" json:"eipAllocationId,omitempty"`
}

func (x *ReserveIpResponse) Reset() {
	*x = ReserveIpResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mchost_ip_payload_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReserveIpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveIpResponse) ProtoMessage() {}

func (x *ReserveIpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mchost_ip_payload_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveIpResponse.ProtoReflect.Descriptor instead.
func (*ReserveIpResponse) Descriptor() ([]byte, []int) {
	return file_proto_mchost_ip_payload_proto_rawDescGZIP(), []int{9}
}

func (x *ReserveIpResponse) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *ReserveIpResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ReserveIpResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReserveIpResponse) GetEipAllocationId() string {
	if x != nil {
		return x.EipAllocationId
	}
	return ""
}

type UnreserveIpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IpId int64 `protobuf:"varint,1,opt,name=ipId,proto3" json:"ipId,omitempty"`
}

func (x *UnreserveIpRequest) Reset() {
	*x = UnreserveIpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mchost_ip_payload_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnreserveIpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnreserveIpRequest) ProtoMessage() {}

func (x *UnreserveIpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mchost_ip_payload_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnreserveIpRequest.ProtoReflect.Descriptor instead.
func (*UnreserveIpRequest) Descriptor() ([]byte, []int) {
	return file_proto_mchost_ip_payload_proto_rawDescGZIP(), []int{10}
}

func (x *UnreserveIpRequest) GetIpId() int64 {
	if x != nil {
		return x.IpId
	}
	return 0
}

type UnreserveIpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error   bool   `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Code    uint32 `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *UnreserveIpResponse) Reset() {
	*x = UnreserveIpResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mchost_ip_payload_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnreserveIpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnreserveIpResponse) ProtoMessage() {}

func (x *UnreserveIpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mchost_ip_payload_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnreserveIpResponse.ProtoReflect.Descriptor instead.
func (*UnreserveIpResponse) Descriptor() ([]byte, []int) {
	return file_proto_mchost_ip_payload_proto_rawDescGZIP(), []int{11}
}

func (x *UnreserveIpResponse) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *UnreserveIpResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UnreserveIpResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UseIpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IpId       int64  `protobuf:"varint,1,opt,name=ipId,proto3" json:"ipId,omitempty"`
	InstanceId string `protobuf:"bytes,2,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
}

func (x *UseIpRequest) Reset() {
	*x = UseIpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mchost_ip_payload_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UseIpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseIpRequest) ProtoMessage() {}

func (x *UseIpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mchost_ip_payload_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseIpRequest.ProtoReflect.Descriptor instead.
func (*UseIpRequest) Descriptor() ([]byte, []int) {
	return file_proto_mchost_ip_payload_proto_rawDescGZIP(), []int{12}
}

func (x *UseIpRequest) GetIpId() int64 {
	if x != nil {
		return x.IpId
	}
	return 0
}

func (x *UseIpRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type UseIpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error   bool   `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Code    uint32 `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *UseIpResponse) Reset() {
	*x = UseIpResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mchost_ip_payload_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UseIpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseIpResponse) ProtoMessage() {}

func (x *UseIpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mchost_ip_payload_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseIpResponse.ProtoReflect.Descriptor instead.
func (*UseIpResponse) Descriptor() ([]byte, []int) {
	return file_proto_mchost_ip_payload_proto_rawDescGZIP(), []int{13}
}

func (x *UseIpResponse) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *UseIpResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UseIpResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UnuseIpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IpId int64 `protobuf:"varint,1,opt,name=ipId,proto3" json:"ipId,omitempty"`
}

func (x *UnuseIpRequest) Reset() {
	*x = UnuseIpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mchost_ip_payload_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnuseIpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnuseIpRequest) ProtoMessage() {}

func (x *UnuseIpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mchost_ip_payload_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnuseIpRequest.ProtoReflect.Descriptor instead.
func (*UnuseIpRequest) Descriptor() ([]byte, []int) {
	return file_proto_mchost_ip_payload_proto_rawDescGZIP(), []int{14}
}

func (x *UnuseIpRequest) GetIpId() int64 {
	if x != nil {
		return x.IpId
	}
	return 0
}

type UnuseIpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error   bool   `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Code    uint32 `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *UnuseIpResponse) Reset() {
	*x = UnuseIpResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mchost_ip_payload_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnuseIpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnuseIpResponse) ProtoMessage() {}

func (x *UnuseIpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mchost_ip_payload_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnuseIpResponse.ProtoReflect.Descriptor instead.
func (*UnuseIpResponse) Descriptor() ([]byte, []int) {
	return file_proto_mchost_ip_payload_proto_rawDescGZIP(), []int{15}
}

func (x *UnuseIpResponse) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *UnuseIpResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UnuseIpResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_mchost_ip_payload_proto protoreflect.FileDescriptor

var file_proto_mchost_ip_payload_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x63, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x69,
	0x70, 0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x14, 0x6d, 0x63, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x70, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x63, 0x68,
	0x6f, 0x73, 0x74, 0x5f, 0x69, 0x70, 0x5f, 0x64, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x55, 0x0a, 0x0f, 0x44, 0x65, 0x66, 0x61,
	0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x3d, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0xb6,
	0x02, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x6c, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61,
	0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6f,
	0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x6f, 0x77,
	0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x49, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x73, 0x70, 0x6f, 0x74, 0x49, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x73,
	0x70, 0x6f, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x22, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x49, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x70, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x69, 0x70, 0x49, 0x64, 0x22, 0x7d, 0x0a, 0x0d, 0x47,
	0x65, 0x74, 0x49, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x28, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d,
	0x63, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x70, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x49, 0x70, 0x52, 0x02, 0x69, 0x70, 0x22, 0x25, 0x0a, 0x0f, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x49, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x69, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x69, 0x70, 0x49,
	0x64, 0x22, 0x56, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x70, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x5e, 0x0a, 0x10, 0x52, 0x65, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x49, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x69, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x69, 0x70, 0x49,
	0x64, 0x12, 0x36, 0x0a, 0x16, 0x73, 0x70, 0x6f, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x16, 0x73, 0x70, 0x6f, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x54,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x22, 0x81, 0x01, 0x0a, 0x11, 0x52, 0x65,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x49, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x65, 0x69, 0x70, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x65, 0x69,
	0x70, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x28, 0x0a,
	0x12, 0x55, 0x6e, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x49, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x69, 0x70, 0x49, 0x64, 0x22, 0x59, 0x0a, 0x13, 0x55, 0x6e, 0x72, 0x65, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x49, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x42, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x49, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x69, 0x70, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x22, 0x53, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x49, 0x70, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x24, 0x0a, 0x0e, 0x55,
	0x6e, 0x75, 0x73, 0x65, 0x49, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x69, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x69, 0x70, 0x49,
	0x64, 0x22, 0x55, 0x0a, 0x0f, 0x55, 0x6e, 0x75, 0x73, 0x65, 0x49, 0x70, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_mchost_ip_payload_proto_rawDescOnce sync.Once
	file_proto_mchost_ip_payload_proto_rawDescData = file_proto_mchost_ip_payload_proto_rawDesc
)

func file_proto_mchost_ip_payload_proto_rawDescGZIP() []byte {
	file_proto_mchost_ip_payload_proto_rawDescOnce.Do(func() {
		file_proto_mchost_ip_payload_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_mchost_ip_payload_proto_rawDescData)
	})
	return file_proto_mchost_ip_payload_proto_rawDescData
}

var file_proto_mchost_ip_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_mchost_ip_payload_proto_goTypes = []interface{}{
	(*Empty)(nil),               // 0: mchost_ip.service.v1.Empty
	(*DefaultResponse)(nil),     // 1: mchost_ip.service.v1.DefaultResponse
	(*CreateIpRequest)(nil),     // 2: mchost_ip.service.v1.CreateIpRequest
	(*CreateIpResponse)(nil),    // 3: mchost_ip.service.v1.CreateIpResponse
	(*GetIpRequest)(nil),        // 4: mchost_ip.service.v1.GetIpRequest
	(*GetIpResponse)(nil),       // 5: mchost_ip.service.v1.GetIpResponse
	(*DeleteIpRequest)(nil),     // 6: mchost_ip.service.v1.DeleteIpRequest
	(*DeleteIpResponse)(nil),    // 7: mchost_ip.service.v1.DeleteIpResponse
	(*ReserveIpRequest)(nil),    // 8: mchost_ip.service.v1.ReserveIpRequest
	(*ReserveIpResponse)(nil),   // 9: mchost_ip.service.v1.ReserveIpResponse
	(*UnreserveIpRequest)(nil),  // 10: mchost_ip.service.v1.UnreserveIpRequest
	(*UnreserveIpResponse)(nil), // 11: mchost_ip.service.v1.UnreserveIpResponse
	(*UseIpRequest)(nil),        // 12: mchost_ip.service.v1.UseIpRequest
	(*UseIpResponse)(nil),       // 13: mchost_ip.service.v1.UseIpResponse
	(*UnuseIpRequest)(nil),      // 14: mchost_ip.service.v1.UnuseIpRequest
	(*UnuseIpResponse)(nil),     // 15: mchost_ip.service.v1.UnuseIpResponse
	(*Ip)(nil),                  // 16: mchost_ip.service.v1.Ip
}
var file_proto_mchost_ip_payload_proto_depIdxs = []int32{
	16, // 0: mchost_ip.service.v1.GetIpResponse.ip:type_name -> mchost_ip.service.v1.Ip
	1,  // [1:1] is the sub-list for method output_type
	1,  // [1:1] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_mchost_ip_payload_proto_init() }
func file_proto_mchost_ip_payload_proto_init() {
	if File_proto_mchost_ip_payload_proto != nil {
		return
	}
	file_proto_mchost_ip_db_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_mchost_ip_payload_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mchost_ip_payload_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DefaultResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mchost_ip_payload_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateIpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mchost_ip_payload_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateIpResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mchost_ip_payload_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mchost_ip_payload_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIpResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mchost_ip_payload_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteIpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mchost_ip_payload_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteIpResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mchost_ip_payload_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReserveIpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mchost_ip_payload_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReserveIpResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mchost_ip_payload_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnreserveIpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mchost_ip_payload_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnreserveIpResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mchost_ip_payload_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UseIpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mchost_ip_payload_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UseIpResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mchost_ip_payload_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnuseIpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mchost_ip_payload_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnuseIpResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_mchost_ip_payload_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_mchost_ip_payload_proto_goTypes,
		DependencyIndexes: file_proto_mchost_ip_payload_proto_depIdxs,
		MessageInfos:      file_proto_mchost_ip_payload_proto_msgTypes,
	}.Build()
	File_proto_mchost_ip_payload_proto = out.File
	file_proto_mchost_ip_payload_proto_rawDesc = nil
	file_proto_mchost_ip_payload_proto_goTypes = nil
	file_proto_mchost_ip_payload_proto_depIdxs = nil
}
