definitions:
  pb.CreateIpRequest:
    properties:
      name:
        type: string
      userId:
        type: integer
    type: object
  pb.DeleteIpRequest:
    properties:
      ipId:
        type: integer
    type: object
  pb.GetIpRequest:
    properties:
      ipId:
        type: integer
    type: object
  pb.UnuseIpRequest:
    properties:
      ipId:
        type: integer
    type: object
  pb.UseIpRequest:
    properties:
      instanceId:
        type: string
      ipId:
        type: integer
    type: object
info:
  contact: {}
paths:
  /create:
    post:
      consumes:
      - application/json
      parameters:
      - description: Request Body
        in: body
        name: requestBody
        required: true
        schema:
          $ref: '#/definitions/pb.CreateIpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Create Ip Fleet Ip
      tags:
      - Ip
  /delete:
    post:
      consumes:
      - application/json
      parameters:
      - description: Request Body
        in: body
        name: requestBody
        required: true
        schema:
          $ref: '#/definitions/pb.DeleteIpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Delete Ip
      tags:
      - Ip
  /get-instance:
    post:
      consumes:
      - application/json
      parameters:
      - description: Request Body
        in: body
        name: requestBody
        required: true
        schema:
          $ref: '#/definitions/pb.GetIpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Get Ip Fleet Instances
      tags:
      - Ip
  /ping:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
      tags:
      - example
  /unuse:
    post:
      consumes:
      - application/json
      parameters:
      - description: Request Body
        in: body
        name: requestBody
        required: true
        schema:
          $ref: '#/definitions/pb.UnuseIpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Unuse Ip
      tags:
      - Ip
  /use:
    post:
      consumes:
      - application/json
      parameters:
      - description: Request Body
        in: body
        name: requestBody
        required: true
        schema:
          $ref: '#/definitions/pb.UseIpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Use Ip
      tags:
      - Ip
swagger: "2.0"
